Repository C-Super/couleur3, pull requests merged in 2023-05, with the labels that each got.

#70 Diagramme de classe, schéma relationnel et contrainte d'intégrité.
  docs/database/diagram-class.md
  docs/database/integrity-constraint.md
  docs/database/relational-schema.md
Labels: documentation, backend

#97 Mise en place de l'environnement de développement
  .devcontainer/devcontainer.json
  .env.example
  composer.lock
  config/cache.php
  docker-compose.yml
  docker/8.2/Dockerfile
  docker/8.2/php.ini
  docker/8.2/start-container
  docker/8.2/supervisord.conf
  docker/mysql/create-testing-database.sh
  docs/environnement/development-environment.md
  docs/environnement/screenshots/dev-container-ports.png
  docs/environnement/screenshots/github-codespaces-close.png
  docs/environnement/screenshots/github-codespaces-create.png
  docs/environnement/screenshots/laravel-welcome.png
  docs/environnement/screenshots/win-clone.png
  docs/environnement/screenshots/win-run-wsl.png
  docs/environnement/screenshots/win-vscode-select-dev-container.png
  package-lock.json
  phpunit.xml
  vite.config.js
Labels: documentation, infrastructure

#98 Configuration de l'intégration continue
  .eslintrc.cjs
  .github/workflows/continuous-integration.yml
  .phpstorm.meta.php
  .prettierrc.json
  Makefile
  _ide_helper.php
  composer.json
  composer.lock
  docs/continuous-integration/continuous-integration.md
  helpers/ModelHelper.php
  package-lock.json
  package.json
  phpstan.neon
  resources/js/app.js
  resources/js/bootstrap.js
  tests/Pest.php
  vite.config.js
Labels: backend, infrastructure

#82 Documentation/diagramme sequences
  docs/diagrammeSequences/animateurActiveChat.md
  docs/diagrammeSequences/animateurChoisiRecompense.md
  docs/diagrammeSequences/animateurDesigneGagnant.md
  docs/diagrammeSequences/animateurInteractionAudio.md
  docs/diagrammeSequences/animateurInteractionCTA.md
  docs/diagrammeSequences/animateurInteractionChoixMultiple.md
  docs/diagrammeSequences/animateurInteractionFin.md
  docs/diagrammeSequences/animateurInteractionPhoto.md
  docs/diagrammeSequences/animateurInteractionSondage.md
  docs/diagrammeSequences/animateurInteractionTexte.md
  docs/diagrammeSequences/animateurInteractionVideo.md
  docs/diagrammeSequences/auditeurGagneRecompense.md
  docs/diagrammeSequences/auditeurParleChat.md
  docs/diagrammeSequences/auditeurRepondAudio.md
  docs/diagrammeSequences/auditeurRepondChoixMultiple.md
  docs/diagrammeSequences/auditeurRepondPhoto.md
  docs/diagrammeSequences/auditeurRepondSondage.md
  docs/diagrammeSequences/auditeurRepondTexte.md
  docs/diagrammeSequences/auditeurRepondVideo.md
  docs/diagrammeSequences/interactionFinit.md
Labels: documentation, frontend-auditeur, backend, frontend-animateur

#110 Improve database configuration
  .devcontainer/devcontainer.json
  Makefile
  app/Http/Controllers/MessageController.php
  app/Models/Address.php
  app/Models/Animator.php
  app/Models/Answer.php
  app/Models/AnswerText.php
  app/Models/Auditor.php
  app/Models/CallToAction.php
  app/Models/Interaction.php
  app/Models/Media.php
  app/Models/Message.php
  app/Models/QuestionChoice.php
  app/Models/Reward.php
  app/Models/Setting.php
  app/Models/Winner.php
  app/Policies/RewardPolicy.php
  database/seeders/AddressSeeder.php
  database/seeders/AnimatorSeeder.php
  database/seeders/AnswerSeeder.php
  database/seeders/AnswerTextSeeder.php
  database/seeders/AuditorSeeder.php
  database/seeders/CallToActionSeeder.php
  database/seeders/InteractionSeeder.php
  database/seeders/MessageSeeder.php
  database/seeders/QuestionChoiceSeeder.php
  database/seeders/RewardSeeder.php
  database/seeders/SettingSeeder.php
  database/seeders/WinnerSeeder.php
  helpers/ModelHelper.php
  resources/js/app.js
  vite.config.js
Labels: backend

#112 Improve form validation on Vue
  .eslintignore
  .eslintrc.cjs
  Makefile
  app/Models/Setting.php
  app/Policies/RewardPolicy.php
  composer.json
  composer.lock
  lang/en.json
  lang/en/auth.php
  lang/en/http-statuses.php
  lang/en/pagination.php
  lang/en/passwords.php
  lang/en/validation.php
  lang/fr.json
  lang/fr/auth.php
  lang/fr/http-statuses.php
  lang/fr/pagination.php
  lang/fr/passwords.php
  lang/fr/validation.php
  package-lock.json
  package.json
  resources/js/Pages/Auth/ConfirmPassword.vue
  resources/js/Pages/Auth/ForgotPassword.vue
  resources/js/Pages/Auth/Login.vue
  resources/js/Pages/Auth/Register.vue
  resources/js/Pages/Auth/ResetPassword.vue
  resources/js/Pages/Auth/VerifyEmail.vue
  resources/js/Pages/Profile/Partials/DeleteUserForm.vue
  resources/js/Pages/Profile/Partials/UpdatePasswordForm.vue
  resources/js/app.js
  resources/js/ziggy.js
  resources/js/zora.js
  routes/auth.php
  vite.config.js
Labels: backend, frontend-animateur
