Repository C-Super/couleur3, pull requests merged in 2023-06, with the labels that each got.

#125 Add deploy config
  .devcontainer/devcontainer.json
  Makefile
  deploy.sh
Labels: infrastructure

#128 Use queue table in prod
  database/migrations/2023_06_02_103436_create_jobs_table.php
Labels: infrastructure

#141 Fix chat getting double messages
  app/Http/Controllers/Animator/DashboardController.php
  app/Http/Controllers/Auditor/DashboardController.php
  app/Http/Controllers/Auth/AuthenticatedSessionController.php
  app/Http/Middleware/ChatEnabled.php
  app/Http/Requests/Auditor/StoreMessageRequest.php
  app/Settings/GeneralSettings.php
  database/settings/2023_06_01_120731_create_general_settings.php
  resources/js/Components/ChatComponent.vue
  resources/js/Pages/Animator/Dashboard.vue
  resources/js/Pages/Auditor/Dashboard.vue
  routes/web.php
Labels: bug, backend

#142 Added pre-commit and pre-push checks and tests
  .husky/pre-commit
  .husky/pre-push
  app/Http/Controllers/Animator/DashboardController.php
  package-lock.json
  package.json
Labels: infrastructure

#150 Feature: Layout du dashboard animateur
  .devcontainer/devcontainer.json
  .env.example
  .phpstorm.meta.php
  _ide_helper.php
  composer.json
  composer.lock
  package-lock.json
  package.json
  resources/js/Components/Bases/BaseButton.vue
  resources/js/Components/Bases/BaseCard.vue
  resources/js/Components/ChatComponent.vue
  resources/js/Components/MessageItem.vue
  resources/js/Pages/Animator/Dashboard.vue
  resources/js/ziggy.js
  tailwind.config.js
Labels: frontend-animateur

#171 Integration doc DM
  docs/Wiki/Backend/continuousIntegration/continuousIntegration.md
  docs/Wiki/Backend/database/classDiagram.md
  docs/Wiki/Backend/database/integrityConstraint.md
  docs/Wiki/Backend/database/relationalSchema.md
  docs/Wiki/Backend/diagrammeSequences/animateurActiveChat.md
  docs/Wiki/Backend/diagrammeSequences/animateurChoisiRecompense.md
  docs/Wiki/Backend/diagrammeSequences/animateurDesigneGagnant.md
  docs/Wiki/Backend/diagrammeSequences/animateurInteractionAudio.md
  docs/Wiki/Backend/diagrammeSequences/animateurInteractionCTA.md
  docs/Wiki/Backend/diagrammeSequences/animateurInteractionChoixMultiple.md
  docs/Wiki/Backend/diagrammeSequences/animateurInteractionFin.md
  docs/Wiki/Backend/diagrammeSequences/animateurInteractionPhoto.md
  docs/Wiki/Backend/diagrammeSequences/animateurInteractionSondage.md
  docs/Wiki/Backend/diagrammeSequences/animateurInteractionTexte.md
  docs/Wiki/Backend/diagrammeSequences/animateurInteractionVideo.md
  docs/Wiki/Backend/diagrammeSequences/auditeurGagneRecompense.md
  docs/Wiki/Backend/diagrammeSequences/auditeurParleChat.md
  docs/Wiki/Backend/diagrammeSequences/auditeurRepondAudio.md
  docs/Wiki/Backend/diagrammeSequences/auditeurRepondChoixMultiple.md
  docs/Wiki/Backend/diagrammeSequences/auditeurRepondPhoto.md
  docs/Wiki/Backend/diagrammeSequences/auditeurRepondSondage.md
  docs/Wiki/Backend/diagrammeSequences/auditeurRepondTexte.md
  docs/Wiki/Backend/diagrammeSequences/auditeurRepondVideo.md
  docs/Wiki/Backend/diagrammeSequences/interactionFinit.md
  docs/Wiki/Backend/environnement/developmentEnvironment.md
  docs/Wiki/Backend/environnement/productionEnvironment.md
  docs/Wiki/Backend/environnement/screenshots/dev-container-ports.png
  docs/Wiki/Backend/environnement/screenshots/github-codespaces-close.png
  docs/Wiki/Backend/environnement/screenshots/github-codespaces-create.png
  docs/Wiki/Backend/environnement/screenshots/laravel-welcome.png
  docs/Wiki/Backend/environnement/screenshots/win-clone.png
  docs/Wiki/Backend/environnement/screenshots/win-run-wsl.png
  docs/Wiki/Backend/environnement/screenshots/win-vscode-select-dev-container.png
Labels: documentation

#179 feat: Création composant interaction radio
  resources/js/Components/Animator/Bases/InteractionRadioGroup.vue
  resources/js/Pages/Animator/Dashboard.vue
  resources/views/app.blade.php
Labels: frontend-animateur

#185 Implémenter le composant tab
  resources/js/Components/Animator/Bases/BaseTab.vue
  resources/js/Components/Animator/Bases/BaseTabs.vue
  resources/js/Pages/Animator/Dashboard.vue
Labels: frontend-animateur

#202 Refactor: animator structure
  .devcontainer/devcontainer.json
  package-lock.json
  package.json
  resources/js/Components/Animator/Bases/BaseRadioGroup.vue
  resources/js/Components/Animator/Bases/BaseTabs.vue
  resources/js/Components/Animator/Chat/ChatView.vue
  resources/js/Components/Animator/Cta/CtaForm.vue
  resources/js/Components/Animator/Question/QuestionForm.vue
  resources/js/Components/Animator/QuickButton/QuickButtonForm.vue
  resources/js/Components/TextInput.vue
  resources/js/Composables/useSubmitInteraction.js
  resources/js/Pages/Animator/Dashboard.vue
  vite.config.js
Labels: frontend-animateur

#200 Feature/composant video stream
  resources/js/Components/Bases/Auditor/Header.vue
  resources/js/Components/Bases/Auditor/Player.vue
  resources/js/Pages/Auditor/Home.vue
Labels: feature, frontend-auditeur

#204 Feature: animator chat
  app/Http/Controllers/Animator/DashboardController.php
  app/Http/Controllers/Auditor/HomeController.php
  resources/js/Components/ChatComponent.vue
  resources/js/Components/MessageItem.vue
  resources/js/Pages/Animator/Dashboard.vue
  resources/js/Pages/Auditor/Home.vue
  resources/js/Utils/date.js
  routes/web.php
Labels: frontend-auditeur, frontend-animateur

#220 Création fichier de méthodologie
  docs/Wiki/GesProj/Gestion de projet.md
  docs/Wiki/GesProj/methodologie.md
Labels: documentation

#221 Feature/composant reponse epingle
  .devcontainer/devcontainer.json
  resources/css/app.css
  resources/js/Components/Animator/Bases/BaseAnswers.vue
  resources/js/Components/Animator/Bases/BaseAnswersSelect.vue
  resources/js/Components/Animator/Question/QuestionForm.vue
  resources/js/Components/ChatComponent.vue
Labels: feature, frontend-animateur

#271 Implement quick click answers
  app/Http/Controllers/InteractionController.php
  app/Http/Requests/StoreInteractionRequest.php
  database/factories/AnswerFactory.php
  database/migrations/2023_05_30_084444_create_call_to_actions_table.php
  database/migrations/2023_05_30_091600_create_answers_table.php
  database/seeders/AuditorSeeder.php
  database/seeders/DatabaseSeeder.php
  helpers/ModelHelper.php
  resources/js/Components/Animator/Answers/AnswersList.vue
  resources/js/Components/Animator/Answers/AnswersRandom.vue
  resources/js/Components/Animator/Answers/AnswersRapidity.vue
  resources/js/Components/Animator/Answers/AnswersSelect.vue
  resources/js/Components/Animator/Bases/BaseAnswers.vue
  resources/js/Components/Animator/Bases/BaseAnswersSelect.vue
  resources/js/Components/Animator/Bases/BaseCard.vue
  resources/js/Components/Animator/Bases/BaseDurationRange.vue
  resources/js/Components/Animator/Bases/BaseTabs.vue
  resources/js/Components/Animator/Chat/ChatView.vue
  resources/js/Components/Animator/QuickClick/QuickClickShow.vue
  resources/js/Enums/Color.js
  resources/js/Pages/Animator/Index.vue
  resources/js/Stores/useInteractionStore.js
  tailwind.config.js
Labels: frontend-animateur

#266 Affichage réponses par réponse sondage/QCM
  resources/js/Components/Animator/Bases/BaseAnswersSimple.vue
Labels: feature, frontend-animateur

#303 Feature: animator quick click rapidity
  app/Http/Controllers/AnimatorController.php
  app/Http/Controllers/InteractionController.php
  app/Http/Controllers/WinnerController.php
  app/Http/Requests/Winner/GenerateWinnersRequest.php
  app/Models/Interaction.php
  resources/js/Components/Animator/Answers/AnswersSelectFastest.vue
  resources/js/Components/Animator/Question/QuestionShow.vue
  resources/js/Components/Animator/QuickClick/QuickClickShow.vue
  resources/js/Pages/Animator/Index.vue
  resources/js/Stores/useInteractionStore.js
  resources/js/ziggy.js
  routes/web.php
Labels: frontend-animateur

#304 163 créer message de remerciement
  resources/js/Components/Animator/Bases/BaseEndingMessage.vue
Labels: feature, frontend-animateur

#313 305 mise a jour affichage message de fin
  resources/js/Components/Animator/Answers/EndingMessage.vue
  resources/js/Components/Animator/Cta/CtaShow.vue
Labels: feature, frontend-animateur

#321 Featue: text auditor submit
  app/Http/Controllers/AnswerController.php
  app/Http/Controllers/WinnerController.php
  app/Http/Requests/Answer/StoreAnswerTextRequest.php
  resources/js/Components/Auditor/Bases/TextInput.vue
  resources/js/Components/Auditor/Home/Popup/PopupText.vue
  resources/js/Components/Auditor/Home/Popups.vue
Labels: frontend-auditeur
